let dia = (prompt("Digite o número da semana: "))

if (dia == "1") {

    console.log("Hoje é segunda, só tistreza")
    
}
else if (dia == "2") {

    console.log("Hoje é terça, começanco a aquecer")
    
}
else if (dia == "3") {

    console.log("Hoje é quarta, só bora")
    
}
else if (dia == "4") {

    console.log("Hoje é quinta, quase lá")
    
}
else if (dia == "5") {

    console.log("SEXTOU!!!")
    
}
else if (dia == "6") {

    console.log("Hoje é sábado, só aleguria")
    
}
else if (dia == "7") {

    console.log("Hoje é domingo, o dia mais feliz e triste da semana")
    
}
else{
console.log("Foi mal, mas não tem dia da semana pra isso não." )
}

